persistence:
  defaultClass: false
  defaultClassReplicaCount: 2

defaultSettings:
  defaultReplicaCount: 2
  backupTargetCredentialSecret: longhorn-backup-credential
  backupTarget: ${backup_target}
  nodeDrainPolicy: always-allow
  taintToleration: node-role.kubernetes.io/storage:NoSchedule

longhornManager:
  tolerations:
    - key: node-role.kubernetes.io/storage
      effect: NoSchedule
